server:
  port: 8089
management:  #actuator
  server:
    port: 8090
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
kafka:
  bootstrapAddress: 127.0.0.1:9092

spring:
  redis:
    host: 127.0.0.1
#    port: 6379
    port: 6666
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 16
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 16
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 1

  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/demo-master?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      initialization-mode: always
      hikari:
        minimum-idle: 20
        maximum-pool-size: 20
        connection-test-query: SELECT 1
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: masterdb-connection-pool
        auto-commit: false
        data-source-properties:
          prepStmtCacheSize: 500
          prepStmtCacheSqlLimit: 20480
          cachePrepStmts: true
          useServerPrepStmts: false
          rewriteBatchedStatements: true
          cacheServerConfiguration: true
          cacheResultSetMetaData: true
          metadataCacheSize: 20480
          maintainTimeStats: false
          # 读取超大数据需要，默认false,一次读取全部
          # useCursorFetch: true
          # defaultFetchSize: 50
          # 压缩传输
          useCompression: true
    slave:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/demo-slave?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      initialization-mode: always
      hikari:
        minimum-idle: 5
        maximum-pool-size: 5
        connection-test-query: SELECT 1
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: slavedb-connection-pool
        auto-commit: false
        data-source-properties:
          prepStmtCacheSize: 500
          prepStmtCacheSqlLimit: 20480
          cachePrepStmts: true
          useServerPrepStmts: false
          rewriteBatchedStatements: true
          cacheServerConfiguration: true
          cacheResultSetMetaData: true
          metadataCacheSize: 20480
          maintainTimeStats: false
          # 读取超大数据需要，默认false,一次读取全部
          # useCursorFetch: true
          # defaultFetchSize: 50
          # 压缩传输
          useCompression: true



