server:
  port: 8089

management:  #actuator
  server:
    port: 8090
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

spring:
  redis:
    host: 127.0.0.1
    port: 6666